name: Implactor
version: IR-1.2
api: [3.0.0-ALPHA12]
main: Implactor\MainIR
author: Zadezter

commands:
    hub:
        description: Teleport/Return to Hub!
        permission: implactor.hub
    sethub:
         description: Set a main hub location point!
         permission: implactor.sethub
    fly:
         description: Turn on/off the fly ability mode!
         permission: implactor.fly
    gmc:
         description: Change your gamemode to Creative mode!
         permission: implactor.gamemode
    gms:
         description: Change your gamemode to Survival mode!
         permission: implactor.gamemode
    gma:
         description: Change your gamemode to Adventure mode!
         permission: implactor.gamemode
    gmspc:
         description: Change your gamemode to Spectator mode!
         permission: implactor.gamemode
    nick:
         description: Set your nickname or default!
         permission: implactor.nick
    wild:
         description: Teleport to random wild spot!
         permission: implactor.wild
    kill:
         description: Kill yourself using command!
         permission: implactor.kill
    ping:
         description: Ping using command!
         permission: implactor.ping
    clearitem:
         description: Clear your items from inventory!
         permission: implactor.clearinventory
    cleararmor:
         description: Clear your equipped armors!
         permission: implactor.cleararmor
    clearall:
         description: Clear all equipped armors or items from your inventory and body!
         permission: implactor.clearall
    heal:
         description: Heal yourself when on emergency!
         permission: implactor.heal
    feed:
         description: Feed yourself when on hunger!
         permission: implactor.feed
    ihelp:
         description: Implactor command info list!
         permission: implactor.command.help
    iabout:
         description: About Implactor plugin!
         permission: implactor.command.about
permissions:
    implactor.*:
     default: op
     description: "Allows all Implactor commands"
    implactor.command.about:
     description: "Allow players to check about Implactor plugin"
     default: true
    implactor.command.help:
     description: "Allow players to use Implactor help command list"
     default: true
    implactor.hub:
     description: "Allow players to use command to return to hub"
     default: true
    implactor.sethub:
     description: "Allow OP staff members to set a main hub"
     default: op
    implactor.wild:
     description: "Allow players to use command to randomly teleport to wild"
     default: true
    implactor.clearinventory:
     description: "Allow OP staff members to clear their inventory"
     default: op
    implactor.cleararmor:
     description: "Allow OP staff members to clear their armors"
     default: op
    implactor.clearall:
     description: "Allow OP staff members to clear all of their items and armors"
     default: op
    implactor.fly:
     description: "Allow players to use command to fly abilities"
     default: true
    implactor.gamemode:
     description: "Allow OP staff members to changed their gamemodes"
     default: op
    implactor.feed:
     description: "Allow OP staff members to feed themselves"
     default: op
    implactor.heal:
     description: "Allow OP staff members to heal themselves"
     default: op
    implactor.kill:
     description: "Allow OP staff members to kill themselves"
     default: op
    implactor.ping:
     description: "Allow players to see their ping status"
     default: true
    implactor.nick:
     description: "Allow players to nick themselves"
     default: true
    implactor.anti:
     description: "Have access with anti advertising/swearing to warn players"
     default: true
