name: Implactor
version: IR-1.0
api: [3.0.0-ALPHA12]
main: Implactor\MainIR
author: Zadezter

commands:
    hub:
        description: Return To Hub!
        permission: implactor.hub
    sethub:
         description: Set a main hub to location point!
         permission: implactor.sethub
     fly:
         description: Fly ability on command!
         permission: implactor.fly
     gmc:
         description: Change your gamemode to Creative!
         permission: implactor.gamemode
     gms:
         description: Change your gamemode to Survival!
         permission: implactor.gamemode
     gma:
         description: Change your gamemode to Adventure!
         permission: implactor.gamemode
     gmspc:
         description: Change your gamemode to Spectator!
         permission: implactor.gamemode
        
permissions:
  implactor.hub:
    default: true
  implactor.doublejump:
    default: true
  implactor.sethub:
    default: op
  implactor.fly:
    default: true
  implactor.gamemode:
    default: op
